language:
  python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install mypy-lang
  - pip install coverage
  - pip install -r requirements.txt

script:
  - mypy --silent-imports --package=opwen_email_server
  - nosetests --with-coverage --cover-branches --cover-erase --cover-package=opwen_email_server
