language:
  python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install coverage
  - pip install -r requirements.txt

script:
  nosetests --with-coverage --cover-branches --cover-erase --cover-package=opwen_cloudserver
